name: fitness_tracker
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Google Fit
  health: ^10.2.0

  # Firebase
  firebase_core: ^2.28.0

  # UI compnenets
  google_fonts: ^6.1.0
  syncfusion_flutter_charts: ^25.1.38
  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.3

  # Permissions
  permission_handler: ^11.3.1

  #state managment
  flutter_riverpod: ^2.4.9
  riverpod_annotation:
  flutter_local_notifications: ^17.0.0

  # Background Management
  flutter_foreground_task: ^6.1.3
  shared_preferences: ^2.2.2
  

  
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner:
  riverpod_generator:
  riverpod_lint:
  custom_lint:

flutter_native_splash:
  color: "#202124"
  image: "assets/logo.png"
  color_dark: "#202124"
  image_dark: "assets/logo.png"

  android_12:
    color: "#202124"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
