name: fitness_tracker
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Google Fit
  health: ^10.2.0

  # Firebase
  firebase_core: ^2.28.0

  # Fonts
  google_fonts: ^6.1.0

  # Permissions
  permission_handler: ^11.3.1

  #state managment
  flutter_riverpod: ^2.4.9
  riverpod_annotation:
  flutter_local_notifications: ^17.0.0
  flutter_notification_channel: ^3.1.0

  # Background Management
  flutter_foreground_task: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner:
  riverpod_generator:
  riverpod_lint:
  custom_lint:

flutter:
  uses-material-design: true
