on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: "Build & Test & Release"

jobs:
  build_and_release:
    name: Build & Test & Release (Main)
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      # Set up Java (if needed for tests)

      # Set up Java 8
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      # Run build_runner
      - run: dart run build_runner build
      # Build APK and IPA
      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      # Test Step
      - name: Run Tests
        run: flutter test

      # Release Step
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
